[project]
name = "test_pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "boto3>=1.38.36",
    "moto>=5.1.5",
    "psycopg2>=2.9.10",
    "pytest>=8.4.0",
    "sqlalchemy>=2.0.41",
]
